runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
